## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environment

development:
  # <<: *AUTHORIZATIONS
  host: 127.0.0.1
  port: 389
  attribute: cn
  #base: <%= ENV["LDAP_BASE_DN"] %>
  #admin_user: <%= ENV["LDAP_ADMIN_USER"] %>
  #admin_password: <%= ENV["LDAP_ADMIN_PASSWD"] %>
  base: dc=my-domain,dc=com
  admin_user: cn=Manager,dc=my-domain,dc=com
  admin_password: secret
  ssl: false

test:
  host: 127.0.0.1
  port: 1389
  attribute: cn
  base: <%= ENV["LDAP_BASE_DN"] %>
  admin_user: <%= ENV["LDAP_ADMIN_USER"] %>
  admin_password: <%= ENV["LDAP_ADMIN_PASSWD"] %>
  ssl: false
  # <<: *AUTHORIZATIONS

production:
  host: ldnfpi-dc01.london.edu
  port: 389
  attribute: cn
  base: <%= ENV["LDAP_BASE_DN"] %>
  admin_user: <%= ENV["LDAP_ADMIN_USER"] %>
  admin_password: <%= ENV["LDAP_ADMIN_PASSWD"] %>
  ssl: false
  # <<: *AUTHORIZATIONS
